/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogue.database.orang;

import dialogue.sirkulasi.*;
import layout.MainFrame;
import static layout.MainFrame.formatter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import layout.Database;
import layout.Laporan;

/**
 *
 * @author GOODWARE1
 */
public class EditDataOrang extends java.awt.Dialog {

    /**
     * Creates new form Edit
     */
    private static String mTitle;
    private static int mRow;
    private static String[] mDatas;

    public EditDataOrang(java.awt.Frame parent, String title, boolean modal, String[] datas, int row) {
        super(parent, title, modal);
        mTitle = title;
        mRow = row;
        mDatas = datas;
        initComponents();
        showSelected(fNama, fAlamat, fNomor, mDatas);
        layout.MainFrame.connect();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fAlamat = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        fNomor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(60, 63, 66));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        fAlamat.setColumns(20);
        fAlamat.setRows(5);
        jScrollPane1.setViewportView(fAlamat);

        jLabel3.setForeground(new java.awt.Color(187, 187, 188));
        jLabel3.setText("Alamat");

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        fNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNomorActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(187, 187, 188));
        jLabel2.setText("Nomor Telepon");

        fNama.setToolTipText("");
        fNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNamaActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(187, 187, 188));
        jLabel1.setText("Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fNama, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addComponent(fNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batal)
                    .addComponent(edit))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        if (fNama.getText().isEmpty() || fNomor.getText().isEmpty()
                || fAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong, silakan coba lagi", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Class.forName(MainFrame.driver);
                Connection kon = DriverManager.getConnection(MainFrame.database, MainFrame.user, MainFrame.pass);
                Statement stt = kon.createStatement();
                String[] data = new String[5];

                data[1] = fNama.getText();
                data[2] = fAlamat.getText();
                data[3] = fNomor.getText();

                String table, kode, nama;

                if (mTitle.contains("Distributor")) {
                    table = "distributor";
                    kode = "kd_dis";
                    nama = "nama_dis";

                } else {
                    table = "pembeli";
                    kode = "kd_pbl";
                    nama = "nama_pbl";
                }

                String SQLUpdate = "UPDATE " + table + " "
                        + "SET " + nama + " = '" + data[1] + "', "
                        + "alamat = '" + data[2] + "', "
                        + "no_telp = '" + data[3] + "' "
                        + " WHERE " + kode + " = " + Integer.parseInt(mDatas[0].substring(4)) + ";";

                stt.execute(SQLUpdate);
                String SQLGetNumber = "SELECT " + kode + " FROM " + table + " WHERE " + nama + " = '" + data[1] + "' ;";
                ResultSet res = stt.executeQuery(SQLGetNumber);

                while (res.next()) {
                    data[0] = res.getString(1);
                }


                if (table.equals("distributor")) {
                    data[0] = Database.koder("DIS", Integer.parseInt(data[0]));
                    Database.distributorTableModel.insertRow(mRow, data);
                    Database.distributorTableModel.removeRow(mRow + 1);

                } else {
                    data[0] = Database.koder("PBL", Integer.parseInt(data[0]));
                    Database.pembeliTableModel.insertRow(mRow, data);
                    Database.pembeliTableModel.removeRow(mRow + 1);

                }

                this.dispose();

            } catch (ClassNotFoundException | NumberFormatException | SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "Peringatan", JOptionPane.WARNING_MESSAGE);
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_editActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        this.dispose();
    }//GEN-LAST:event_batalActionPerformed

    private void fNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNomorActionPerformed
        editActionPerformed(evt);
    }//GEN-LAST:event_fNomorActionPerformed

    private void fNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNamaActionPerformed
        fAlamat.requestFocus();
    }//GEN-LAST:event_fNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            EditDataOrang dialog = new EditDataOrang(new java.awt.Frame(), mTitle, true, mDatas, mRow);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    public static void showSelected(JTextField fNama, JTextArea fAlamat, JTextField fNomor,  String[] datas) {
        fNama.setText(datas[1]);
        fAlamat.setText((datas[2]));
        fNomor.setText(datas[3]);
    }

    public static String takeNominal(String nominal) {
        String[] hasilArray = nominal.substring(4).split("\\.");
        String hasil = "";
        for (int i = 0; i < hasilArray.length; i++) {
            hasil += hasilArray[i];
        }

        return hasil;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton edit;
    private javax.swing.JTextArea fAlamat;
    private javax.swing.JTextField fNama;
    private javax.swing.JTextField fNomor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
