/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogue.database.minuman;

import com.toedter.calendar.JDateChooser;
import dialogue.database.orang.*;
import dialogue.sirkulasi.*;
import layout.MainFrame;
import static layout.MainFrame.formatter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import layout.Database;
import layout.Sirkulasi;

/**
 *
 * @author GOODWARE1
 */
public class EditDataMinuman extends java.awt.Dialog {

    /**
     * Creates new form Edit
     */
    private static String mTitle;
    private static int mRow;
    private static String[] mDatas;

    public EditDataMinuman(java.awt.Frame parent, String title, boolean modal, String[] datas, int row) {
        super(parent, title, modal);
        mTitle = title;
        mRow = row;
        mDatas = datas;
        initComponents();
        TambahDataMinuman.getNamaSupplierToComboBox(comboDistributor);
        showSelected(fMerk, comboUkuran, comboIsi, fStok, fHargaBeli, fHargaJual, fTanggal, comboDistributor, mDatas);
        layout.MainFrame.connect();
        fHargaBeli.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {
                fHargaBeli.setText(formatter(EditDataMinuman.takeNominal(fHargaBeli.getText())));
            }
        });

        fHargaJual.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {
                fHargaJual.setText(formatter(EditDataMinuman.takeNominal(fHargaJual.getText())));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        fMerk = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fStok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboIsi = new javax.swing.JComboBox<>();
        fTanggal = new com.toedter.calendar.JDateChooser();
        batal = new javax.swing.JButton();
        fHargaJual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboUkuran = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboDistributor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        fHargaBeli = new javax.swing.JTextField();

        setBackground(new java.awt.Color(60, 63, 66));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(187, 187, 188));
        jLabel2.setText("Stok");

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        fMerk.setToolTipText("");
        fMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fMerkActionPerformed(evt);
            }
        });

        label.setForeground(new java.awt.Color(187, 187, 188));
        label.setText("Harga Jual");

        jLabel3.setForeground(new java.awt.Color(187, 187, 188));
        jLabel3.setText("Ukuran");

        fStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fStokActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(187, 187, 188));
        jLabel4.setText("Harga Beli");

        comboIsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Isi Perdus", "12", "24", "48" }));
        comboIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIsiActionPerformed(evt);
            }
        });

        fTanggal.setDateFormatString("dd-MM-yyyy");

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        fHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fHargaJualActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(187, 187, 188));
        jLabel5.setText("Isi");

        comboUkuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Ukuran", "1500", "1200", "660" }));
        comboUkuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUkuranActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(187, 187, 188));
        jLabel1.setText("Merk");

        jLabel7.setForeground(new java.awt.Color(187, 187, 188));
        jLabel7.setText("Distributor");

        comboDistributor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Distributor" }));

        jLabel6.setForeground(new java.awt.Color(187, 187, 188));
        jLabel6.setText("Tanggal Masuk");

        fHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fHargaBeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboIsi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboDistributor, 0, 229, Short.MAX_VALUE)
                        .addComponent(fMerk, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .addComponent(fHargaBeli, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .addComponent(fTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboUkuran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fStok))
                    .addComponent(fHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboIsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(fHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboDistributor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit)
                    .addComponent(batal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        if (fMerk.getText().isEmpty()
                || comboUkuran.getSelectedIndex() == 0
                || comboIsi.getSelectedIndex() == 0
                || fStok.getText().isEmpty()
                || fTanggal.getDate() == null
                || fHargaBeli.getText().isEmpty()
                || fHargaJual.getText().isEmpty()
                || comboDistributor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong, silakan coba lagi", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Class.forName(MainFrame.driver);
                Connection kon = DriverManager.getConnection(MainFrame.database, MainFrame.user, MainFrame.pass);
                Statement stt = kon.createStatement();
                String[] data = new String[9];

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                data[0] = TambahDataMinuman.generateKodeMinuman(fMerk.getText(), comboUkuran.getSelectedIndex(), fTanggal.getDate());
                data[1] = fMerk.getText();
                data[2] = comboUkuran.getSelectedItem().toString();
                data[3] = comboIsi.getSelectedItem().toString();
                data[4] = fStok.getText();
                data[5] = EditDataOrang.takeNominal(fHargaBeli.getText());
                data[6] = EditDataOrang.takeNominal(fHargaJual.getText());
                data[7] = sdf.format(fTanggal.getDate());
                data[8] = comboDistributor.getSelectedIndex() + "";

                //remove "-" from kd_min
                String[] kodes = mDatas[0].split("-");
                mDatas[0] = "";
                for (String kode : kodes) {
                    mDatas[0] += kode;
                }

                String SQLUpdate = "UPDATE minuman "
                        + "SET kd_min = '" + data[0] + "', "
                        + "nama_min = '" + data[1] + "', "
                        + "ukuran = '" + data[2] + "', "
                        + "isi = '" + data[3] + "', "
                        + "stok = '" + data[4] + "', "
                        + "harga_beli = '" + data[5] + "', "
                        + "harga_jual = '" + data[6] + "', "
                        + "tgl_masuk = '" + data[7] + "', "
                        + "kd_dis = '" + data[8] + "' "
                        + " WHERE kd_min " + " = '" + mDatas[0] + "' ;";

                stt.execute(SQLUpdate);

                //reformat data to frontend
                data[0] = data[0].substring(0, 3) + "-"
                        + data[0].substring(3, 7) + "-" + data[0].substring(7, 13);

                data[2] = data[2] + " ml";

                data[5] = MainFrame.formatter(data[5]);
                data[6] = MainFrame.formatter(data[6]);

                DateFormat df
                        = new SimpleDateFormat("dd MMMM yyyy", new Locale("in", "ID"));

                DateFormat sqlDateFormat
                        = new SimpleDateFormat("yyyy-MM-dd");

                data[7] = df.format(sqlDateFormat.parse(data[7]));

                data[8] = comboDistributor.getSelectedItem().toString();

                Database.minumanTableModel.insertRow(mRow, data);
                Database.minumanTableModel.removeRow(mRow + 1);

                this.dispose();

            } catch (ClassNotFoundException | NumberFormatException | SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "Peringatan", JOptionPane.WARNING_MESSAGE);
                System.out.println(ex.getMessage());

            } catch (ParseException ex) {
                Logger.getLogger(TambahDataMinuman.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_editActionPerformed

    private void fMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fMerkActionPerformed
        comboUkuran.requestFocus();
    }//GEN-LAST:event_fMerkActionPerformed

    private void fStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fStokActionPerformed
        fHargaBeli.requestFocus();
    }//GEN-LAST:event_fStokActionPerformed

    private void comboIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIsiActionPerformed
        fStok.requestFocus();
    }//GEN-LAST:event_comboIsiActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        this.dispose();
    }//GEN-LAST:event_batalActionPerformed

    private void fHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fHargaJualActionPerformed

    private void comboUkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUkuranActionPerformed
        comboIsi.requestFocus();
    }//GEN-LAST:event_comboUkuranActionPerformed

    private void fHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fHargaBeliActionPerformed
        editActionPerformed(evt);
    }//GEN-LAST:event_fHargaBeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            EditDataMinuman dialog = new EditDataMinuman(new java.awt.Frame(), mTitle, true, mDatas, mRow);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    public static void showSelected(JTextField fMerk, JComboBox comboUkuran, JComboBox comboIsi,
            JTextField fStok, JTextField fHargaBeli, JTextField fHargaJual, JDateChooser fTanggal, JComboBox comboDistributor,
            String[] datas) {

        fMerk.setText(datas[1]);
        comboUkuran.setSelectedItem(datas[2].substring(0, datas[2].length() - 3));
        comboIsi.setSelectedItem(datas[3]);
        fStok.setText(datas[4]);
        fHargaBeli.setText(datas[5]);
        fHargaJual.setText(datas[6]);

        DateFormat df
                = new SimpleDateFormat("dd MMMM yyyy", new Locale("in", "ID"));

        try {
            fTanggal.setDate(df.parse(datas[7]));
        } catch (ParseException ex) {
            Logger.getLogger(EditDataMinuman.class.getName()).log(Level.SEVERE, null, ex);
        }

        comboDistributor.setSelectedItem(datas[8]);
    }

    public static String takeNominal(String nominal) {
        String[] hasilArray = nominal.substring(4).split("\\.");
        String hasil = "";
        for (int i = 0; i < hasilArray.length; i++) {
            hasil += hasilArray[i];
        }

        return hasil;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> comboDistributor;
    private javax.swing.JComboBox<String> comboIsi;
    private javax.swing.JComboBox<String> comboUkuran;
    private javax.swing.JButton edit;
    private javax.swing.JTextField fHargaBeli;
    private javax.swing.JTextField fHargaJual;
    private javax.swing.JTextField fMerk;
    private javax.swing.JTextField fStok;
    private com.toedter.calendar.JDateChooser fTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
