/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import dialogue.database.minuman.EditDataMinuman;
import dialogue.database.minuman.TambahDataMinuman;
import dialogue.database.orang.EditDataOrang;

import dialogue.sirkulasi.HapusSirkulasi;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import static layout.Database.distributorTableModel;
import static layout.Database.minumanTableModel;
import static layout.Database.pembeliTableModel;
import static layout.MainFrame.formatter;

/**
 *
 * @author GOODWARE1
 */
public class Penjualan extends javax.swing.JInternalFrame {

    private int mSatuan = 0;
    private int mRow = 0;
    private int mStok = 0;
    private int mSubTotal = 0;
    private int mNota = 0;

    private int pembeliSelectedRow = -1;
    private int mGrandTotal;

    public Penjualan() {
        initComponents();
        hideTitleBar();
        MainFrame.connect();
        getToComboBox(comboIDMinuman, comboPembeli);
        TPenjualan.setModel(penjualanTableModel);
        backToStart();
        comboPembeli.addItemListener(new ComboPembeliListener());
        comboIDMinuman.addItemListener(new ComboMinumanListener());
        spinnerJumlah.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                fStokMin.setText(((mStok
                        - Integer.parseInt(spinnerJumlah.getValue().toString())) + ""));

                mSubTotal = mSatuan * Integer.parseInt(spinnerJumlah.getValue() + "");

                fHargaMin.setText(MainFrame.formatter(((mSubTotal + ""))));

            }

        });
        fUangMasuk.setText(" Rp  ");
        fUangMasuk.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {
                fUangMasuk.setText(formatter(EditDataMinuman.takeNominal(fUangMasuk.getText())));

                fKembalian.setText(MainFrame.formatter((Integer.parseInt(EditDataMinuman.takeNominal(fUangMasuk.getText()))
                        - Integer.parseInt(EditDataMinuman.takeNominal(fTotal.getText())))
                        + ""));

            }
        });

        setTanggaldanNota();

    }

    private void backToStart() {
        penjualanTableModel.getDataVector().removeAllElements();
        mGrandTotal = 0;
    }

    private void hideTitleBar() {
        setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI hide = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) hide).setNorthPane(null);
    }

    public static javax.swing.table.DefaultTableModel penjualanTableModel = mhSupplierTableModel();

    private static javax.swing.table.DefaultTableModel mhSupplierTableModel() {

        return new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"No. Item", "Kode Minuman", "Nama Minuman", "Harga Satuan", "Jumlah", "Sub Total"}
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false

            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        fKembalian = new javax.swing.JTextField();
        batal = new javax.swing.JButton();
        simpanPenjualan = new javax.swing.JButton();
        hapusDataMinuman = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPenjualan = new javax.swing.JTable();
        comboIDMinuman = new javax.swing.JComboBox<>();
        spinnerJumlah = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dealButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fTanggal = new javax.swing.JTextField();
        fNota = new javax.swing.JTextField();
        fUangMasuk = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fNamaMin = new javax.swing.JTextField();
        fHargaMin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fStokMin = new javax.swing.JTextField();
        comboPembeli = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        fTotal = new javax.swing.JTextField();
        fNamaPembeli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fUkuran = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fIsi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(60, 63, 66));

        panel.setBackground(new java.awt.Color(60, 63, 66));

        fKembalian.setEditable(false);
        fKembalian.setBackground(new java.awt.Color(69, 73, 75));
        fKembalian.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fKembalian.setForeground(new java.awt.Color(187, 187, 188));
        fKembalian.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fKembalianActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        simpanPenjualan.setText("Simpan penjualan");
        simpanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPenjualanActionPerformed(evt);
            }
        });

        hapusDataMinuman.setText("Hapus Item Minuman");
        hapusDataMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDataMinumanActionPerformed(evt);
            }
        });

        TPenjualan.setBackground(new java.awt.Color(60, 63, 66));
        TPenjualan.setForeground(new java.awt.Color(187, 187, 188));
        TPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TPenjualan);

        comboIDMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Minuman" }));

        spinnerJumlah.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinnerJumlah.setValue(1);

        jLabel1.setForeground(new java.awt.Color(187, 187, 188));
        jLabel1.setText("Jumlah");

        jLabel2.setForeground(new java.awt.Color(187, 187, 188));
        jLabel2.setText("Kode Minuman");

        dealButton.setText("Deal");
        dealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(60, 63, 63));
        jPanel1.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 187, 188));
        jLabel3.setText("Nota       ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(187, 187, 188));
        jLabel4.setText("Tanggal ");

        fTanggal.setEditable(false);

        fNota.setEditable(false);
        fNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNotaActionPerformed(evt);
            }
        });

        fUangMasuk.setBackground(new java.awt.Color(69, 73, 75));
        fUangMasuk.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fUangMasuk.setForeground(new java.awt.Color(187, 187, 188));
        fUangMasuk.setText(" ");
        fUangMasuk.setCaretColor(new java.awt.Color(187, 187, 188));
        fUangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fUangMasukActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(187, 187, 188));
        jLabel10.setText("Uang Masuk");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(187, 187, 188));
        jLabel13.setText("Kembalian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fUangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fNota, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fUangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        fNamaMin.setEditable(false);

        fHargaMin.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(187, 187, 188));
        jLabel5.setText("Nama Minuman");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(187, 187, 188));
        jLabel6.setText("Harga Jual");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(187, 187, 188));
        jLabel7.setText("Nama Pembeli");

        fStokMin.setEditable(false);

        comboPembeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pembeli" }));

        jLabel8.setForeground(new java.awt.Color(187, 187, 188));
        jLabel8.setText("Kode Pembeli");

        fTotal.setEditable(false);
        fTotal.setBackground(new java.awt.Color(69, 73, 75));
        fTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fTotal.setForeground(new java.awt.Color(187, 187, 188));
        fTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTotalActionPerformed(evt);
            }
        });

        fNamaPembeli.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(187, 187, 188));
        jLabel9.setText("Stok");

        fUkuran.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(187, 187, 188));
        jLabel11.setText("Isi per dus");

        fIsi.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(187, 187, 188));
        jLabel12.setText("Ukuran");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(187, 187, 188));
        jLabel14.setText("Total Bayar");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(simpanPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(fNamaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12)
                        .addGap(21, 21, 21)
                        .addComponent(fUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(comboPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(comboIDMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(spinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fStokMin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(fHargaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(dealButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addContainerGap())
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel11)
                                .addGap(27, 27, 27)
                                .addComponent(fIsi))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hapusDataMinuman))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboIDMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealButton)
                    .addComponent(comboPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fStokMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fHargaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(fNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNamaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(fUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fIsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapusDataMinuman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpanPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        comboIDMinuman.setSelectedIndex(0);
        comboPembeli.setSelectedIndex(0);
        TPenjualan.clearSelection();
        penjualanTableModel.setRowCount(0);

        mRow = 0;

        fTotal.setText("");
        fUangMasuk.setText("Rp ");
        fKembalian.setText("");

        comboPembeli.setEnabled(true);
    }//GEN-LAST:event_batalActionPerformed

    private void fTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTotalActionPerformed

    private void fUangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fUangMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fUangMasukActionPerformed

    private void fKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fKembalianActionPerformed

    private void dealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealButtonActionPerformed
        mStok = mStok - Integer.parseInt(spinnerJumlah.getValue() + "") ;
        if (comboPembeli.getSelectedIndex() != 0 && comboIDMinuman.getSelectedIndex() != 0 && mStok >= 0) {
            mRow++;

            mGrandTotal = 0;
            String[] data = new String[6];

            data[0] = mRow + "";
            data[1] = comboIDMinuman.getSelectedItem().toString() + "";
            data[2] = fNamaMin.getText();
            data[3] = MainFrame.formatter(mSatuan + "");
            data[4] = spinnerJumlah.getValue() + "";
            data[5] = MainFrame.formatter(mSubTotal + "");

            penjualanTableModel.addRow(data);

            for (int i = 0; i < mRow; i++) {

                mGrandTotal += Integer.parseInt(
                        EditDataOrang.takeNominal(penjualanTableModel.getValueAt(i, 5) + ""));

            }

            
           
            fStokMin.setText(mStok+"");
            fTotal.setText(MainFrame.formatter(mGrandTotal + ""));
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "Peringatan", JOptionPane.WARNING_MESSAGE);
            mStok = mStok + Integer.parseInt(spinnerJumlah.getValue() + "") ;
        }

    }//GEN-LAST:event_dealButtonActionPerformed

    private void simpanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPenjualanActionPerformed

        try {

            for (int i = 0; i < mRow; i++) {
                Class.forName(MainFrame.driver);
                Connection kon = DriverManager.getConnection(MainFrame.database, MainFrame.user, MainFrame.pass);
                Statement stt = kon.createStatement();

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                String SQL = "INSERT INTO penjualan VALUES ("
                        + mNota + ", '"
                        + sdf.format(Calendar.getInstance().getTime()) + "', '"
                        + penjualanTableModel.getValueAt(i, 1) + "', "
                        + comboPembeli.getSelectedIndex() + ", "
                        + EditDataOrang.takeNominal(penjualanTableModel.getValueAt(i, 3) + "") + ", "
                        + penjualanTableModel.getValueAt(i, 4) + " , "
                        + EditDataOrang.takeNominal(penjualanTableModel.getValueAt(i, 5) + "") + " "
                        + ") ;";

                stt.execute(SQL);
                stt.close();

                Statement stt1 = kon.createStatement();
                String SQL1 = "UPDATE minuman set stok = stok - " + penjualanTableModel.getValueAt(i, 4) 
                        + " where kd_min = '" + penjualanTableModel.getValueAt(i, 1) + "' ;" ;
                        

                stt1.execute(SQL1);
                stt1.close();

                kon.close();

            }

            batalActionPerformed(evt);

            mNota++;
            fNota.setText(mNota + "");
            comboPembeli.setEnabled(true);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_simpanPenjualanActionPerformed

    private void hapusDataMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDataMinumanActionPerformed
        if (TPenjualan.getSelectedRow() != -1 && TPenjualan.getRowCount() != 0) {
            penjualanTableModel.removeRow(TPenjualan.getSelectedRow());
            TPenjualan.clearSelection();
            mRow--;
            mGrandTotal = 0;

            for (int i = 0; i < mRow; i++) {

                mGrandTotal += Integer.parseInt(
                        EditDataOrang.takeNominal(penjualanTableModel.getValueAt(i, 5) + ""));
            }

            fTotal.setText(MainFrame.formatter(mGrandTotal + ""));
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih pembeli dan minuman terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_hapusDataMinumanActionPerformed

    private void fNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNotaActionPerformed

    public static void getToComboBox(JComboBox comboBox, JComboBox comboBox2) {
        try {
            Class.forName(MainFrame.driver);
            Connection kon = DriverManager.getConnection(MainFrame.database, MainFrame.user, MainFrame.pass);
            Statement stt = kon.createStatement();
            String SQLMinuman = "select * from minuman";
            ResultSet res = stt.executeQuery(SQLMinuman);

            while (res.next()) {
                comboBox.addItem(res.getString(1));

            }
            res.close();
            stt.close();

            Statement sttPembeli = kon.createStatement();
            String SQLPembeli = "select * from pembeli";
            ResultSet resPembeli = sttPembeli.executeQuery(SQLPembeli);

            while (resPembeli.next()) {
                comboBox2.addItem(Database.koder("PBL", Integer.parseInt(resPembeli.getString(1))));

            }
            resPembeli.close();
            sttPembeli.close();

            kon.close();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TambahDataMinuman.class
                    .getName()).log(Level.SEVERE, null, ex);

        }
    }

    class ComboMinumanListener implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent event) {
            if (event.getStateChange() == ItemEvent.SELECTED && comboIDMinuman.getSelectedIndex() != 0) {
                try {
                    //get the selected item from combo box
                    String item = event.getItem().toString();

                    Class.forName(MainFrame.driver);
                    Connection kon = DriverManager.getConnection(MainFrame.database, MainFrame.user, MainFrame.pass);
                    Statement stt = kon.createStatement();

                    String SQL = "SELECT nama_min, harga_jual, stok, ukuran, isi FROM minuman WHERE kd_min = '" + item + "' ;";
                    ResultSet res = stt.executeQuery(SQL);

                    while (res.next()) {
                        fNamaMin.setText(res.getString(1));

                        mSatuan = Integer.parseInt(res.getString(2));
                        mSubTotal = mSatuan;
                        fHargaMin.setText(MainFrame.formatter(mSubTotal + ""));
                        mStok = Integer.parseInt(res.getString(3));
                        fStokMin.setText(mStok + "");
                        fUkuran.setText(res.getString(4) + " ml");
                        fIsi.setText(res.getString(5));

                    }

                    spinnerJumlah.setModel(new SpinnerNumberModel(0, 0, mStok, 1));

                    res.close();
                    stt.close();
                    kon.close();

                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (comboIDMinuman.getSelectedIndex() == 0) {
                fNamaMin.setText("");
                fHargaMin.setText("");
                fStokMin.setText("");
                fUkuran.setText("");
                fIsi.setText("");
                spinnerJumlah.setValue(0);

            }
        }
    }

    class ComboPembeliListener implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent event) {
            if (event.getStateChange() == ItemEvent.SELECTED && comboPembeli.getSelectedIndex() != 0) {
                try {
                    //get the selected item from combo box
                    String item = event.getItem().toString();

                    Class.forName(MainFrame.driver);
                    Connection kon = DriverManager.getConnection(MainFrame.database, MainFrame.user, MainFrame.pass);
                    Statement stt = kon.createStatement();

                    String SQL = "SELECT * from pembeli where kd_pbl = " + comboPembeli.getSelectedIndex() + " ;";
                    ResultSet res = stt.executeQuery(SQL);

                    while (res.next()) {
                        fNamaPembeli.setText(res.getString(2));
                    }

                    res.close();
                    stt.close();
                    kon.close();

                    comboPembeli.setEnabled(false);

                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (comboPembeli.getSelectedIndex() == 0) {
                fNamaPembeli.setText("");
            }

        }
    }

    private void setTanggaldanNota() {

        try {
            DateFormat df
                    = new SimpleDateFormat("dd MMMM yyyy", new Locale("in", "ID"));

            fTanggal.setText(df.format(Calendar.getInstance().getTime()));

            Class.forName(MainFrame.driver);
            Connection kon = DriverManager.getConnection(MainFrame.database, MainFrame.user, MainFrame.pass);
            Statement stt = kon.createStatement();

            String SQL = "SELECT max(nomor_nota) FROM penjualan";
            ResultSet res = stt.executeQuery(SQL);

            while (res.next()) {
                if (res.getString(1) != null) {
                    mNota = Integer.parseInt(res.getString(1)) + 1;
                    fNota.setText(mNota + "");

                } else {
                    mNota = 1;
                    fNota.setText(mNota + "");
                }
            }

            res.close();
            stt.close();
            kon.close();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Penjualan.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TPenjualan;
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> comboIDMinuman;
    private javax.swing.JComboBox<String> comboPembeli;
    private javax.swing.JButton dealButton;
    private javax.swing.JTextField fHargaMin;
    private javax.swing.JTextField fIsi;
    public static javax.swing.JTextField fKembalian;
    private javax.swing.JTextField fNamaMin;
    private javax.swing.JTextField fNamaPembeli;
    private javax.swing.JTextField fNota;
    private javax.swing.JTextField fStokMin;
    private javax.swing.JTextField fTanggal;
    public static javax.swing.JTextField fTotal;
    public static javax.swing.JTextField fUangMasuk;
    private javax.swing.JTextField fUkuran;
    private javax.swing.JButton hapusDataMinuman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JButton simpanPenjualan;
    private javax.swing.JSpinner spinnerJumlah;
    // End of variables declaration//GEN-END:variables
}
